LIST_OF_PROFESSORS = [
    "Monika Aidelsburger",
    "Milan P. Allan",
    "Matthias Althammer",
    "Christian Back",
    "Pramod Bhatotia",
    "Sebastian Blatt",
    "Immanuel Bloch",
    "Holger Boche",
    "Dominique Bougeard",
    "Martin Brandt",
    "Dominik B. Bucher",
    "Daniel Burgarth",
    "Christian Carlowitz",
    "Juan Ignacio Cirac",
    "J. Ignacio Cirac",
    "Frank Deppe",
    "Christian Deppe",
    "Vladimir Dyakonov",
    "Claudia Eckert",
    "Dmitri K. Efetov",
    "Christopher Eichler",
    "Jens Eisert",
    "Kirill G. Fedorov",
    "Stefan Filipp",
    "Jonathan Finley",
    "Simon Fölling",
    "Steffen J. Glaser",
    "Milena Grifoni",
    "Rudolf Gross",
    "Michael J. Hartmann",
    "Bert Hecht",
    "Albert Heuberger",
    "Sven Hoefling",
    "Alexander Högele",
    "Alexander Holleitner",
    "Hans Huebl",
    "Christian Jirauschek",
    "Michael Knap",
    "Johannes Knolle",
    "Robert Koenig",
    "Dieter Kranzlmüller",
    "Barbara Kraus",
    "Christoph Kutter",
    "Claudia Linnhoff-Popien",
    "Jeanette Miriam Lorenz",
    "Juergen Lorenz",
    "Florian Marquardt",
    "Alexander Martin",
    "Achim Marx",
    "Wolfgang Mauerer",
    "Christian B. Mendl",
    "Roland Nagy",
    "Janis Nötzel",
    "Lode Pollet",
    "Frank Pollmann",
    "Nikolas Pomplun",
    "Peter Rabl",
    "Andreas Reiserer",
    "Giorgio Sangiovanni",
    "Markus Sauer",
    "Christian Schilling",
    "Kai Phillip Schmidt",
    "Ulrich Schollwöck",
    "Thomas Schulte-Herbrüggen",
    "Martin Schulz",
    "Helmut Seidl",
    "Andreas Stute",
    "Marc Tornow",
    "Tobias Vogl",
    "Jan von Delft",
    "Joachim von Zanthier",
    "Heiko B. Weber",
    "Robert Wille",
    "Johannes Zeiher"
]

LIST_OF_PROFESSORS_NOT_MQV = [
    "Fakher Assaad",
    "Mikhail Belkin",
    "Mónica Benito González",
    "Matthias Bode",
    "Annabelle Bohrdt",
    "Felix Büttner",
    "Livio Chioncel",
    "Martin Eckstein",
    "Jaroslav Fabian",
    "Philipp Gegenwart",
    "Fabian Grusdt",
    "Jad C. Halimeh",
    "Philipp Hansmann",
    "Markus Heyl",
    "Peter Hommelhoff",
    "Sebastian Klembt",
    "Jakob Kottmann",
    "Vojislav Krstic",
    "John Lupton",
    "Janina Maultzsch",
    "Fabian Pauly",
    "Friedrich Reinert",
    "Klaus Richter",
    "Vahid Sandoghdar",
    "Ronny Thomale",
    "Martin Vossiek",
    "Eva Weig",
    "Robert Weigel",
    "Harald Weinfurter",
    "Dieter Weiss"
]






